String es_dir = "elasticsearch"
String ls_dir = "logstash"
String kb_dir = "kibana"
String fb_dir = "filebeat"

String es_regex = "**/${es_dir}/**"
String ls_regex = "**/${ls_dir}/**"
String kb_regex = "**/${kb_dir}/**"
String fb_regex = "**/${fb_dir}/**"

def remote = [:]
remote.name = 'buildserver'
remote.host = '100.0.0.1'
remote.user = 'ladmin'
remote.password = 'P@ssw0rd'
remote.allowAnyHosts = true   

pipeline {

    agent any

    stages {

        stage("Checkout code") {
            steps {
                git url: 'http://100.0.0.2:3000/zeus/pipeline.git'
            }
        }
        
        stage("Sanity check") {
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/tests/sanity-test.yaml"
            }
            post{
                failure {
                    script{
                        error "Sanity check failed, exiting now..."
                    }
                }
            }
        }
        
        /* --------------------------- Elasticsearch ---------------------------*/

        stage("BUILD Elasticsearch") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/elasticsearch/deploy.yaml"
            }
            post{
                failure {
                    script{
                        error "Elasticsearch deployment failed, exiting now..."
                    }
                }
            }
        }
        
        stage("TEST Elasticsearch") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/elasticsearch/test.yaml"
            }
            post{
                failure {
                    script{
                        error "Elasticsearch test failed, exiting now..."
                    }
                }
            }
        }

        /* --------------------------- Logstash ---------------------------*/
    
        stage("BUILD Logstash") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/logstash/deploy.yaml"
            }
            /* since it's not really used by anything atm, this can fail but the job can continue */
        }
        
        stage("TEST Logstash") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/logstash/test.yaml"
            }
        }

        /* --------------------------- Kibana ---------------------------*/

        stage("BUILD Kibana") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/kibana/deploy.yaml"
            }
            post{
                failure {
                    script{
                        error "Kibana deployment failed, exiting now..."
                    }
                }
            }
        }
        
        stage("TEST Kibana") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/kibana/test.yaml"
            }
            post{
                failure {
                    script{
                        error "Kibana test failed, exiting now..."
                    }
                }
            }
        }

        /* --------------------------- Filebeat ---------------------------*/

        stage("BUILD Filebeat") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/filebeat/deploy.yaml"
            }
            post{
                failure {
                    script{
                        error "Filebeat deployment failed, exiting now..."
                    }
                }
            }
        }
        
        stage("TEST Filebeat") {
           when { 
                anyOf {
                    expression {params.DEPLOY == "everything"} ;
                    changeset es_regex 
                }
            }
            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/filebeat/test.yaml"
            }
            post{
                failure {
                    script{
                        error "Filebeat test failed, exiting now..."
                    }
                }
            }
        }

        /* --------------------------- Mo testing ---------------------------*/

        stage("TEST Security") {

            steps {
                sshCommand remote: remote, command: "ansible-playbook -i /mnt/challenge/hosts /mnt/challenge/app/prod/tests/security-test.yaml"
            }
        }
        
        /* --------------------------- Landing ---------------------------*/

        stage("Cleanup and Report") {

            steps {
                echo "Sending report with email and deleting build artefacts"
            }
        }

    }
}